---
docker_repo:
  channel:
    stable_enabled: true
    test_enabled: false
    nightly_enabled: false

docker_dependencies:
- acl
- python3-ruamel.yaml
- python3-pip
- python3-docker
- python3-requests
- python3-urllib3
- python3-virtualenv
- net-tools
- iproute2
- gpg

gpg_url: https://repo.mecan.ir/repository/debian-docker/gpg # https://download.docker.com/linux/ubuntu/gpg
repo_url: https://repo.mecan.ir/repository/debian-docker # https://download.docker.com/linux

docker_packages:
- containerd.io
- docker-ce
- docker-buildx-plugin
- docker-ce-cli
- docker-compose-plugin
- docker-scan-plugin
- docker-ce-rootless-extras

docker_config:
  proxy:
    enabled: true
    http_proxy:
    https_proxy:
    no_proxy:
  mirror_registry:
    enabled: true
    urls:


  insecure_registry:
    enabled: true

  live_restor:
