---
# System Configuration and Maintenance
- name: ---- Deploy Lynis security auditor ----
  ansible.builtin.unarchive:
    src: lynis-3.1.3.tar.gz
    dest: /opt/
    remote_src: no
    keep_newer: yes
  tags: lynis

- name: ---- Update RedHat-based System Packages ----
  yum:
    name: '*'
    state: latest
    update_cache: yes
  tags: packages_update

- name: ---- Configure DNS resolver ----
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 644
  tags: shekan

- name: ---- Install Epel-Release Package ----
  dnf:
    name: epel-release
    state: present
  tags: install_epel

- name: ---- Install RedHat Essential Tools ----
  dnf:
    name: "{{redhat_tools}}"
    state: present
  tags: redhat_tools

- name: ---- Set system hostname ----
  ansible.builtin.hostname:
    name: "{{hostname}}"
  tags: hostname

# Bootstrap Python3 and test        
- name: ---- Install Python3 in RedHat ----
  raw: dnf install -y python3
  tags: RedHat_python3
