debian_tools:
- wget
- git
- vim
- bash-completion
- curl
- htop
- net-tools
- dnsutils
- atop
- sudo
- software-properties-common
- telnet
- axel
- jq
- iotop
- ca-certificates
- gnupg
- lsb-release
- apt-transport-https
- gpg
- tmux

hostname: Debian-12
